x-vars: &x-vars
  REGISTRY_STORAGE: s3
  REGISTRY_STORAGE_S3_SECURE: true
  REGISTRY_STORAGE_S3_REGION: auto
  REGISTRY_STORAGE_S3_ENCRYPT: false
  REGISTRY_STORAGE_S3_BUCKET: cri-cr
  REGISTRY_STORAGE_DELETE_ENABLED: true
  REGISTRY_STORAGE_S3_SKIPVERIFY: false
  REGISTRY_STORAGE_S3_CHUNKSIZE: 104857600
  REGISTRY_STORAGE_S3_REGIONENDPOINT: https://ACCOUNT_ID.r2.cloudflarestorage.com/

x-registry: &x-registry
  restart: always
  image: registry:2.8.3
  deploy:
    mode: global
  secrets:
    - r2_access_key
    - r2_secret_key
  entrypoint: [
    "sh",
    "-xc",
    "REGISTRY_STORAGE_S3_ACCESSKEY=`cat /run/secrets/r2_access_key` REGISTRY_STORAGE_S3_SECRETKEY=`cat /run/secrets/r2_secret_key` registry serve /etc/docker/registry/config.yml"
  ]
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'
  networks:
    registry:

services:
  reverse_proxy:
    hostname: reverse_proxy
    container_name: reverse_proxy
    image: nginx:latest
    restart: always
    deploy:
      mode: global
    ports:
      - target: 8080
        published: 80
        mode: host
        protocol: tcp
    secrets:
      - nginx_config_file
      - nginx_js_file
    networks:
      registry:
    entrypoint: [ "sh",
                  "-xc",
                  "sed -i 's@user  nginx;@load_module modules/ngx_http_js_module.so;user  nginx;@g' /etc/nginx/nginx.conf && cp /run/secrets/nginx_js_file /etc/nginx/conf.d/mirror.js && cp /run/secrets/nginx_config_file /etc/nginx/conf.d/default.conf  && nginx -g \"daemon off;\""
    ]



  registry-mirror:
    <<: *x-registry
    environment:
      <<: *x-vars
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
      REGISTRY_PROXY_USERNAME:
      REGISTRY_PROXY_PASSWORD:

  registry-private:
    <<: *x-registry
    environment:
      <<: *x-vars

secrets:
  r2_access_key:
    file: files/r2-access-key.txt
  r2_secret_key:
    file: files/r2-secret-key.txt
  nginx_config_file:
    file: files/nginx.conf
  nginx_js_file:
    file: files/mirror.js

networks:
  registry: