x-registry: &x-registry
  restart: always
  image: registry:2.8.3
  deploy:
    mode: global
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'
  networks:
    registry:
  volumes:
    - registry:/var/lib/registry:rw

services:
  reverse_proxy:
    hostname: reverse_proxy
    container_name: reverse_proxy
    image: nginx:latest
    restart: always
    deploy:
      mode: global
    ports:
      - target: 8080
        published: 80
        mode: host
        protocol: tcp
    secrets:
      - nginx_config_file
      - nginx_js_file
    networks:
      registry:
    entrypoint: [ "sh",
                  "-xc",
                  "sed -i 's@user  nginx;@load_module modules/ngx_http_js_module.so;user  nginx;@g' /etc/nginx/nginx.conf && cp /run/secrets/nginx_js_file /etc/nginx/conf.d/mirror.js && cp /run/secrets/nginx_config_file /etc/nginx/conf.d/default.conf  && nginx -g \"daemon off;\""
    ]



  registry-mirror:
    <<: *x-registry
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
      REGISTRY_PROXY_USERNAME:
      REGISTRY_PROXY_PASSWORD:

  registry-private:
    <<: *x-registry

secrets:
  nginx_config_file:
    file: files/nginx.conf
  nginx_js_file:
    file: files/mirror.js

networks:
  registry:

volumes:
  registry:
    name: registry
    driver: local
    driver_opts:
      type: volume
      o: "bind"
      device: "/nfs/registry"
