{
 "title": "All Analytics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "🚀 N+B+K+V+G+C",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "### Self-Hosted \n### Analytics"
   }
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM analytics.data WHERE timestamp >= $__fromTime AND timestamp <=  $__toTime"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct type) from data WHERE timestamp >= $__fromTime AND timestamp <=  $__toTime;"
    }
   ]
  },
  {
   "title": "New Vistors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH vistors_before as (SELECT user_id\n                        FROM analytics.data\n                        where timestamp < $__fromTime\n                        group by user_id)\nSELECT count(users) as total\nFROM (SELECT count(*) as users FROM analytics.data WHERE timestamp >= $__fromTime AND timestamp <=  $__toTime AND user_id NOT IN (select user_id from vistors_before) GROUP BY user_id); "
    }
   ]
  },
  {
   "title": "Unique Vistors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH sessions as (SELECT distinct user_id from data WHERE timestamp >= $__fromTime AND timestamp <=  $__toTime group by user_id)\nselect count(*)\nfrom sessions;"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH sessions as (SELECT distinct session_id from data WHERE timestamp >= $__fromTime AND timestamp <=  $__toTime group by session_id)\nselect count(*)\nfrom sessions;"
    }
   ]
  },
  {
   "title": "Average Session",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH times as (SELECT session_id,\n                      max(timestamp)                    as end_of_session,\n                      min(timestamp)                    as start_of_session,\n                      end_of_session - start_of_session as delta_ts\n               FROM data\n               WHERE timestamp >= $__fromTime AND timestamp <=  $__toTime\n               GROUP BY session_id\n               ORDER BY session_id)\n\nSELECT avg(delta_ts)\nfrom times;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(device_brand ILIKE 'apple' AND isNotNull(device_brand))                                       AS apple,\r\n       sum(device_brand ILIKE 'google' AND isNotNull(device_brand))                                      AS google,\r\n       sum(isNull(device_brand) OR (device_brand NOT ILIKE 'apple' AND device_brand NOT ILIKE 'google')) AS unknown_brand,\r\n           sum(data.device_type ILIKE 'smartphone' AND isNotNull(data.device_type))                                       AS mobile,\r\n    sum(data.device_type ILIKE 'pc' AND isNotNull(data.device_type))                                      AS desktop,\r\n    sum(isNull(data.device_type) OR (data.device_type NOT ILIKE 'smartphone' AND data.device_type NOT ILIKE 'pc')) AS unknown_type\r\n\r\nfrom data\r\n    WHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime;"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT country_code as metric, count(*) as value  FROM data WHERE $__timeFilter(`timestamp`) GROUP BY country_code;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT country_name, count(*) as Total, concat(country_name, ' - ', Total) as Country FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by country_name ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT city_name, count(*) as Total, concat(city_name, ' - ', Total) as City FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by city_name ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT path, count(*) as Total\nFROM data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\nGROUP BY path\nORDER BY Total DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 9, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT browser_name, count(*) as Total FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by browser_name ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT initcap(device_type), count(*) as Total FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by device_type ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 15, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT initcap(device_os_name), count(*) as Total FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by device_os_name ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 2, "x": 18, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT type, count(*) as Total FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by type ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 2, "x": 20, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT device_brand, count(*) as Total FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by device_brand ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 2, "x": 22, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT upper(locale), count(*) as Total  FROM analytics.data\nWHERE timestamp >=  $__fromTime AND timestamp <=  $__toTime\ngroup by locale ORDER BY Total DESC \nLIMIT 10;"
    }
   ]
  }
 ]
}