services:
  demo:
    build:
      context: .
      dockerfile: version1/Dockerfile
#      dockerfile: version2/Dockerfile
    networks:
      demo:

  nginx:
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8090:80
    networks:
      demo:

networks:
  demo:
